### ISSUE TITLE
iPad mini 2 downgrade error: Unsupported model.../Traceback (most recent call last)

### ISSUE THREAD

**Issue by mikeytance** [MatthewPierson/Vieux#140]
**Describe the issue**
I had followed the steps to downgrade the iOS, but the screen reminds me that "
ERROR: normal_idevice_new: can't open device with UDID 00008020-001B65621104003A
ERROR: Unable to discover device mode. Please make sure a device is attached.
ERROR: Unsupported model...
Exiting..." or "Traceback (most recent call last):
  File "./vieux", line 89, in <module>
    ipsw.unzipIPSW(argv[2])
  File "/Users/george/Desktop/Vieux-master/ipsw.py", line 153, in unzipIPSW
    pwndfumode()
  File "/Users/george/Desktop/Vieux-master/restore.py", line 22, in pwndfumode
    device = dfu.acquire_device()
  File "/Users/george/Desktop/Vieux-master/resources/ipwndfu/dfu.py", line 20, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available"
after "./vieux -i iOS path"

<img width="568" alt="Screen Shot 2020-04-25 at 09 20 09" src="https://user-images.githubusercontent.com/32946161/80267994-a7873200-86d6-11ea-999a-75da956871ff.png">
<img width="568" alt="Screen Shot 2020-04-25 at 09 19 56" src="https://user-images.githubusercontent.com/32946161/80268008-c7b6f100-86d6-11ea-909a-a6389d7302d8.png">
![Uploading Screen Shot 2020-04-25 at 09.20.09.png…]()

**Computer (please complete the following information):**
 - MacBook Pro Retina  (early 2015)
 - MacOS Catalina Version 10.15.4
 - Python 2.7.16 / Python 3.8.2
 - Vieux 1.0.1

**iOS Device (please complete the following information):**
 - iPad4,4
 - iOS 12.4.6

**Comment by flipped154** [comment]
same

**Comment by Dogtor-san** [comment]
anyone have the solutions? tried fix #1, catalinafix but no change

**Comment by RadicalR** [comment]
I got around this by installing homebrew for mac and running "brew install libusb"
