### ISSUE TITLE
ModuleNotFoundError: No module named 'bsdiff4'

### ISSUE THREAD

**Issue by Gortob** [MatthewPierson/Vieux#161]
Need help with this error please:

Traceback (most recent call last):
  File "/Users/name/Downloads/Vieux-master/vieux", line 6, in <module>
    import ipsw
  File "/Users/name/Downloads/Vieux-master/ipsw.py", line 3, in <module>
    import bsdiff4
ModuleNotFoundError: No module named 'bsdiff4'

**Comment by hx2nn** [comment]
我也一样
Traceback (most recent call last):
  File "vieux", line 6, in <module>
    import ipsw
  File "/Users/hanxin/Downloads/Vieux-master/ipsw.py", line 3, in <module>
    import bsdiff4
ModuleNotFoundError: No module named 'bsdiff4'

**Comment by 0x1Dx** [comment]
我也是这样

**Comment by cxjava** [comment]
@0x1Dx @hx2nn @Gortob 

try this command ` python3 -m pip install -r requirements.txt `

**Comment by nihaoyunfei** [comment]
thanks

**Comment by nihaoyunfei** [comment]
thanks

**Comment by JannikCrack** [comment]
> > @0x1Dx @hx2nn @Gortob
> > try this command `python3 -m pip install -r requirements.txt`
> 
> Thanks! This fixed my problem

if I do this I get this error:
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects

**Comment by wehoit** [comment]
I get the same error as JannikCrack
Did it get resolved?
