### ISSUE TITLE
Running setup.py install for bsdiff4 ... Error

### ISSUE THREAD

**Issue by DakgalbiBandit** [MatthewPierson/Vieux#162]
Describe the issue
Terminal shows these lines when running Vieux through Terminal. I have been trying to figure out what is wrong by reading the readme.md, but I'm not finding any solutions:
```
Running setup.py install for bsdiff4 ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-dq90a8b_/bsdiff4/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-dq90a8b_/bsdiff4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-7grs_ox4/install-record.txt --single-version-externally-managed --compile
         cwd: /private/tmp/pip-install-dq90a8b_/bsdiff4/
    Complete output (17 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/bsdiff4
    copying bsdiff4/test_all.py -> build/lib.macosx-10.9-x86_64-3.8/bsdiff4
    copying bsdiff4/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/bsdiff4
    copying bsdiff4/format.py -> build/lib.macosx-10.9-x86_64-3.8/bsdiff4
    copying bsdiff4/cli.py -> build/lib.macosx-10.9-x86_64-3.8/bsdiff4
    running build_ext
    building 'bsdiff4.core' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    creating build/temp.macosx-10.9-x86_64-3.8/bsdiff4
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c bsdiff4/core.c -o build/temp.macosx-10.9-x86_64-3.8/bsdiff4/core.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-dq90a8b_/bsdiff4/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-dq90a8b_/bsdiff4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-7grs_ox4/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```
**Screenshots**
<img width="1280" alt="Screen Shot 2020-06-03 at 9 46 41 PM" src="https://user-images.githubusercontent.com/66365765/83633115-c20ccf00-a5e3-11ea-8dc5-7ee63265f848.png">

**Computer (please complete the following information):**
 - Computer Model: [Macbook Pro Early 2015 (Retina, 13-inch)]
 - MacOS Version [MacOS Catalina 10.15.4]
 - Python Version [Python3.8.3]
 - Vieux Version [Latest version 6/3/20]

**iOS Device (please complete the following information):**
REQUIRED -
 - Device: [iPad2,5]
 - Desired Version: [8.4.1]

**Additional context**
Do I have to re-install both Python3 and Python2? Is this an issue with the newer version of Catalina OS?

**Comment by MatthewPierson** [comment]
You need to install the developer command line tools. Install them by running "xcode-select --install" and following its prompts

**Comment by DakgalbiBandit** [comment]
> You need to install the developer command line tools. Install them by running "xcode-select --install" and following its prompts

Thank you. This method worked. 

Another question. Since the iPad Mini 1st Gen is a 32-bit device, I don't have to put it in DFU mode  during the whole process. However, it seems that Vieux puts the iPad Mini into recovery mode as soon as I reach this line `Device is not running iOS 10.x, using normal TFP0 kloader...` and it just takes me back to `Vieux-master %`. Am I doing something wrong?

**The whole command**
```
Device is not running iOS 10.x, using normal TFP0 kloader...
Please press the home button on your device or unplug and replug it back in.
Waiting 10 seconds for you to do this.
Getting SHSH...
Traceback (most recent call last):
  File "./vieux", line 89, in <module>
    ipsw.unzipIPSW(argv[2])
  File "/Users/wonjinum/Downloads/Vieux-master/ipsw.py", line 142, in unzipIPSW
    createCustomIPSW32(fname)
  File "/Users/wonjinum/Downloads/Vieux-master/ipsw.py", line 372, in createCustomIPSW32
    restore32(model, iosversion)
  File "/Users/wonjinum/Downloads/Vieux-master/restore.py", line 230, in restore32
    ecid = localdevice.getecid()
  File "/Users/wonjinum/Downloads/Vieux-master/device.py", line 82, in getecid
    device = dfu.acquire_device()
  File "/Users/wonjinum/Downloads/Vieux-master/resources/ipwndfu/dfu.py", line 20, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
```

**Comment by MatthewPierson** [comment]
You need to install libusb. You can do so with "brew install libusb", Vieux places the device into PWNDFU mode via kloader which is needed to perform the downgrade

**Comment by DakgalbiBandit** [comment]
> You need to install libusb. You can do so with "brew install libusb", Vieux places the device into PWNDFU mode via kloader which is needed to perform the downgrade

I have installed libusb, but the same problem occurs. Once it reaches this line `Device is not running iOS 10.x, using normal TFP0 kloader...`, vieux puts my connected iPad Mini into recovery mode. Do I have to put my iPad Mini into DFU mode? Since the 9.3.5 Phoenix Pwn jailbreak is semi-tethered, the jailbreak won't work once the device is in DFU mode. 

```
Connecting to device via SSH...
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/client.py:835: UserWarning: Unknown ssh-rsa host key for 192.168.1.110: b'834ab6d55f0e549e4460b5dad38468c2'
  warnings.warn(
Device is not running iOS 10.x, using normal TFP0 kloader...
Please press the home button on your device or unplug and replug it back in.
Waiting 10 seconds for you to do this.
Getting SHSH...
ERROR: No Apple device in DFU Mode 0x1227 detected after 30.00 second timeout. Exiting.
Place the device into DFU mode again and re-run Vieux
```
