### ISSUE TITLE
iPad bypass

### ISSUE THREAD

**Issue by brosey** [MatthewPierson/Vieux#171]
vieux program wont load on terminal mac

macs-MBP-4:~ mac$ /Users/mac/Desktop/Vieux-master/vieux 
Traceback (most recent call last):
  File "/Users/mac/Desktop/Vieux-master/vieux", line 6, in <module>
    import ipsw
  File "/Users/mac/Desktop/Vieux-master/ipsw.py", line 3, in <module>
    import bsdiff4
ModuleNotFoundError: No module named 'bsdiff4'
macs-MBP-4:~ mac$

**Comment by brosey** [comment]
<img width="568" alt="Screen Shot 2020-06-23 at 22 44 57" src="https://user-images.githubusercontent.com/67341287/85452100-36afa980-b5a3-11ea-88ca-1b83bcde32a9.png">


any assistance will be appreciated

**Comment by eatingurtoes** [comment]
Install dependencies

**Comment by RealSilentPirate** [comment]
Try pip3 -r requirements.txt

If it doesn't work try this:
https://github.com/MatthewPierson/Vieux/issues/95#issuecomment-599255377
So basically this command:
python3 -m pip install --user -r requirements.txt
