### ISSUE TITLE
usb.core.USBError: [Errno None] Other error

### ISSUE THREAD

**Issue by csyhoyang** [MatthewPierson/Vieux#22]
admindeMac-mini:Vieux-master admin$ python3 vieux -i "PATH/TO/~/Downloads/iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw"
Given IPSW Path is PATH/TO/~/Downloads/iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw
Vieux - A tool for 32/64 Bit OTA downgrades
Still in BETA so expect issues/broken things
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in normal mode
Starting IPSW unzipping
Invalid filepath/filename.
Please try again with a valid filepath/filename.
Enter the path to the IPSW file (Or drag and drop the IPSW into this window):
/Users/admin/Downloads/iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw 
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
Traceback (most recent call last):
  File "vieux", line 48, in <module>
    ipsw.unzipIPSW(path)
  File "/Users/admin/Downloads/Vieux-master/ipsw.py", line 119, in unzipIPSW
    pwndfumode()
  File "/Users/admin/Downloads/Vieux-master/restore.py", line 20, in pwndfumode
    device = dfu.acquire_device()
  File "/Users/admin/Downloads/Vieux-master/resources/ipwndfu/dfu.py", line 19, in acquire_device
    usb.util.claim_interface(device, 0)
  File "/usr/local/lib/python3.7/site-packages/usb/util.py", line 205, in claim_interface
    device._ctx.managed_claim_interface(device, interface)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/local/lib/python3.7/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/local/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno None] Other error

**Comment by csyhoyang** [comment]
osx 10.14.6

**Comment by MatthewPierson** [comment]
I will be closing this issue in 24 hours if you no longer need help/the issue has been resolved. If you still need help then comment with what you need and I will not close it.

**Comment by semyonnov** [comment]
Macbook 2009 Mojave 10.14.6 6,1 errors: 
raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno None] Other error

somebody solve this mistake
