### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by master90x** [MatthewPierson/Vieux#222]
Hi.
I'm using Mac Air Mid 2012 and Catalina 15.7 latest to downgrade Ipad mini 2 4.4 to ios 10.3.3 from 12.4.9
Installed Python 3.8.6 and pip3, libusb

First I using Python 3.9 but this bug was shown, I downgrade to Python 3.8 bug this bug still exist
When i downgrade Ipad mini 2 from 12.4.9 to 10.3.3 this bug is shown. Someone help me!

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 806, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'IPSW/Firmware/all_flash/sep-firmware.j85.RELEASE.im4p' -> 'resources/other/sep.im4p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/Downgrade/Vieux-master/./vieux", line 89, in <module>
    ipsw.unzipIPSW(argv[2])
  File "/Users/mac/Desktop/Downgrade/Vieux-master/ipsw.py", line 154, in unzipIPSW
    createCustomIPSW64(fname, devicemodel)
  File "/Users/mac/Desktop/Downgrade/Vieux-master/ipsw.py", line 499, in createCustomIPSW64
    shutil.move("IPSW/Firmware/all_flash/sep-firmware.j85.RELEASE.im4p", "resources/other/sep.im4p")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 820, in move
    copy_function(src, real_dst)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'resources/other/sep.im4p'
```

**Comment by lazybri** [comment]
hey man,mine is getting more or less similar output, have you figured it out yet?

**Comment by lazybri** [comment]
my python version is 3.9.1, don't know if that is a problem.

**Comment by master90x** [comment]
> 
> 
> my python version is 3.9.1, don't know if that is a problem.

I dont know. Firstly i run this tool with newest python version 3.9.1 but get this problem. After that i downgrade python to 3.8.6 but this problem still exist. do you have some solution for this case?
