### ISSUE TITLE
Unable to downgrade on my iPad Airs(macOS 10.15.1, iPad Air 4,1)

### ISSUE THREAD

**Issue by Godlike1125** [MatthewPierson/Vieux#28]
Starting iBSS/iBEC patching
Looks like you are downgrading an iPad Air to 10.3.3!
Patched iBSS/iBEC
About to re-build IPSW
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'IPSW/Firmware/all_flash/sep-firmware.j71.RELEASE.im4p' -> 'resources/other/sep.im4p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vieux", line 75, in <module>
    ipsw.unzipIPSW(argv[2])
  File "/Users/me/Desktop/Vieux-master/ipsw.py", line 147, in unzipIPSW
    createCustomIPSW64(fname, devicemodel)
  File "/Users/me/Desktop/Vieux-master/ipsw.py", line 320, in createCustomIPSW64
    shutil.move("IPSW/Firmware/all_flash/sep-firmware.j71.RELEASE.im4p", "resources/other/sep.im4p")
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'resources/other/sep.im4p'

**//I tried on both of my iPad Airs it shows the same error. Please Help.**

**Comment by MatthewPierson** [comment]
I have fixed this error in the latest update, please download the latest files and try again @Godlike1125 and let me know if it fixes it or not

**Comment by Godlike1125** [comment]
[errorlogrestore.txt](https://github.com/MatthewPierson/Vieux/files/3981719/errorlogrestore.txt)


I gave it a couple tries on using the latest master now it stopped at this error message twice.

**Comment by MatthewPierson** [comment]
Please try with the latest commit, it has a potential fix for this issue but I can't test myself as I don't have any A7 iPads (This is the same message I'm replying to all relevant issues :) )

**Comment by Godlike1125** [comment]
I really appreciate your response. Yeah can't blame you for not having an iPad to jailbreak lol. now it's giving me an error -6. Please see attached error log.
[errorlogrestore.txt](https://github.com/MatthewPierson/Vieux/files/3986779/errorlogrestore.txt)

**Comment by MatthewPierson** [comment]
@Godlike1125 Fixed in latest commit, please give it a try!
