### ISSUE TITLE
usb.core.USBError: [Errno None] Other error

### ISSUE THREAD

**Issue by kaajikentir** [MatthewPierson/Vieux#40]
hi , my ip5s 6,1 booted on dfu correctly but i got this error on Mojave 10.14.6 again and again . how to solve pls need reply :(

Vieux - A tool for 32/64 Bit OTA downgrades
Still in BETA so expect issues/broken things
If you are using a 64 Bit device then connect it in DFU Mode
If you are using a 32 Bit device then just have it connected in NORMAL mode
Files cleaned.
/Users/kaajioi/Desktop/Vieux-master/iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw is a zip archive!
Starting IPSW unzipping
Continuing...
IPSW found at given path...
Cleaning up old files...
Files cleaned.
Unzipping..
Traceback (most recent call last):
  File "./vieux", line 79, in <module>
    ipsw.unzipIPSW(argv[2])
  File "/Users/kaajioi/Desktop/Vieux-master/ipsw.py", line 153, in unzipIPSW
    pwndfumode()
  File "/Users/kaajioi/Desktop/Vieux-master/restore.py", line 22, in pwndfumode
    device = dfu.acquire_device()
  File "/Users/kaajioi/Desktop/Vieux-master/resources/ipwndfu/dfu.py", line 23, in acquire_device
    usb.util.claim_interface(device, 0)
  File "/usr/local/lib/python3.7/site-packages/usb/util.py", line 205, in claim_interface
    device._ctx.managed_claim_interface(device, interface)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/local/lib/python3.7/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/local/lib/python3.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno None] Other error
KaaJis-MacBook:Vieux-master kaajioi$

**Comment by MatthewPierson** [comment]
What MacBook are you using? Is it a pre 2012 model?

**Comment by kaajikentir** [comment]
two different macbook sir , 5,1 mojave patcher dodsdude and md101 both showing that error . neither i run on el capitan it showing device unsupported wihout that error , and iam understand your tool work perfectly on mojave but i didnt know that error came

**Comment by kaajikentir** [comment]
once again , when am run on elcapitan my device is very easy to enter pwndfu , not on mojave idk why?

**Comment by MatthewPierson** [comment]
Old MacBooks from around 2011/2010 and earlier are not supported. There’s nothing I can do about it sorry

**Comment by MatthewPierson** [comment]
I will be closing this issue in 24 hours if you no longer need help/the issue has been resolved. If you still need help then comment with what you need and I will not close it.

**Comment by kaajikentir** [comment]
ok i'll close it , may i ask your tool ota downgrader master still support on old macbook ?

**Comment by merzota** [comment]
I have late 13 MacBook Pro and the same error 

> Traceback (most recent call last):
  File "rmsigchks.py", line 114, in <module>
    main()
  File "rmsigchks.py", line 107, in main
    device.ctrl_transfer(HOST2DEVICE, DFU_ABORT, 0, 0, 0, 0)
  File "/Users/Skipper/Desktop/Vieux-master2/resources/ipwndfu/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/Users/Skipper/Desktop/Vieux-master2/resources/ipwndfu/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/Users/Skipper/Desktop/Vieux-master2/resources/ipwndfu/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error
