### ISSUE TITLE
Exception: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by thekkeith55** [MatthewPierson/Vieux#55]
I am trying to downgrade my 4s, and when i shsh into it it gives me this long error 
```
traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/packet.py", line 609, in _read_timeout
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/paramiko/transport.py", line 2215, in _check_banner
    raise SSHException(
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

ERROR: SSH/SCP failed, make sure that you are jailbroken with OpenSSH installed, try rebooting the device
Exiting...
```

**Comment by MatthewPierson** [comment]
Have you made sure that SSH is working on the device? Just open a new SSH connection to the device to verify that 1, OpenSSH is installed, 2, it is running and working, and 3, that you are able to connect to the device from outside of Vieux. Also if you haven't rebooted after installing OpenSSH then try that, sometimes OpenSSH doesn't start correctly after installing on some 32 Bit devices.

**Comment by thekkeith55** [comment]
Yes, OpenSSH is installed. but I tried it again and it just acts like OpenSSH is not running I tried opening the SSH tunnel on 3utools, on my windows computer and that worked. 
```
Please enter your devices IP address (Find it in WiFi settings):
192.168.1.24
Please enter the root password to your device (Default is 'alpine'):

Connecting to device via SSH...
ERROR: SSH/SCP failed, make sure that you are jailbroken with OpenSSH installed, try rebooting the device
Exiting...
```
