### ISSUE TITLE
python issue with usb iPhone 5s

### ISSUE THREAD

**Issue by hashidan** [MatthewPierson/Vieux#6]
Traceback (most recent call last):
  File "./vieux", line 48, in <module>
    ipsw.unzipIPSW(path)
  File "/Users/user/Vieux/ipsw.py", line 110, in unzipIPSW
    pwndfumode()
  File "/Users/user/Vieux/restore.py", line 20, in pwndfumode
    device = dfu.acquire_device()
  File "/Users/hoangseidel/Vieux/resources/ipwndfu/dfu.py", line 16, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/usr/local/lib/python3.7/site-packages/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

**Comment by hashidan** [comment]
needed to install libusb, that fixed the issue for me
