### ISSUE TITLE
Process Failed Right Before It Began

### ISSUE THREAD

**Issue by dihbao197** [MatthewPierson/Vieux#75]
Please press the home button on your device or unplug and replug it back in.
Waiting 10 seconds for you to do this.
Getting SHSH...
Traceback (most recent call last):
  File "vieux", line 85, in <module>
    ipsw.unzipIPSW(argv[2])
  File "/Users/dinhbao/Downloads/Vieux-master/ipsw.py", line 142, in unzipIPSW
    createCustomIPSW32(fname)
  File "/Users/dinhbao/Downloads/Vieux-master/ipsw.py", line 346, in createCustomIPSW32
    restore32(model, iosversion)
  File "/Users/dinhbao/Downloads/Vieux-master/restore.py", line 230, in restore32
    ecid = localdevice.getecid()
  File "/Users/dinhbao/Downloads/Vieux-master/device.py", line 82, in getecid
    device = dfu.acquire_device()
  File "/Users/dinhbao/Downloads/Vieux-master/resources/ipwndfu/dfu.py", line 20, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

**Comment by MatthewPierson** [comment]
Run "brew install libusb"
